version: 2.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest

    steps:
      - checkout

      # Deploy to Kubernetes
      - run:
          name: Deploy to Kubernetes
          command: |
            echo $GCP_OIDC >> kubeconfig.json
            echo $gcp_oidc >> kubeconfigs.json
            pwd && ls -lhtr
            cat kubeconfig.json && cat kubeconfigs.json
            #kubectl apply -f path/to/your/kubernetes/manifests/



      # # Build your Docker image
      # - setup_remote_docker:
      #     version: 20.10.7
      # - run:
      #     name: Build Docker image
      #     command: docker build -t my-app:latest .

      # Push the Docker image to Docker Hub
      # - run:
      #     name: Push Docker image
      #     command: |
      #       docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      #       docker tag my-app:latest $DOCKER_USERNAME/my-app:latest
      #       docker push $DOCKER_USERNAME/my-app:latest

  deploy:
    docker:
      - image: google/cloud-sdk:latest

    steps:
      - setup_remote_docker:
          version: 20.10.7

      # Deploy to Kubernetes
      - run:
          name: Deploy to Kubernetes
          command: |
            echo ${GCP_OICD} >> kubeconfig.json
            pwd
            # cat kubeconfig.json && cat ../nginx.yml
            #kubectl apply -f path/to/your/kubernetes/manifests/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
